# Generated by Django 6.0.3 on 2026-04-06 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0002_alter_registrar_options_remove_registrar_date_hired_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'Registrar', 'verbose_name_plural': 'List of Registrars'},
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='school_registrar.registrar')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['-created_at'],
            },
        ),
    ]
