# Generated by Django 6.0.3 on 2026-04-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0005_alter_registrar_options_alter_folder_cabinet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='category',
            field=models.CharField(choices=[('Basic Education', 'Basic Education'), ('College Education', 'College Education')], default='Basic Education', max_length=30),
        ),
    ]
