# Generated by Django 6.0.3 on 2026-04-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0006_registrar_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Folder', 'verbose_name_plural': '- b. Folders'},
        ),
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'Registrar', 'verbose_name_plural': '- a. Registrars'},
        ),
    ]
