# Generated by Django 6.0 on 2026-04-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0007_alter_folder_options_alter_registrar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Folder', 'verbose_name_plural': '- b. List of Syllabus'},
        ),
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'Registrar', 'verbose_name_plural': '- a. List of Registrars'},
        ),
    ]
