# Generated by Django 6.0 on 2026-04-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0008_alter_folder_options_alter_registrar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'Registrar', 'verbose_name_plural': '- a. List of Members'},
        ),
    ]
