# Generated by Django 6.0 on 2026-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0009_alter_registrar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='category',
            field=models.CharField(choices=[('Basic Education', "Basic Education Institution (BEI's)"), ('College Education', "Higher Education Institution (HEI's)")], default='Basic Education', max_length=30),
        ),
    ]
