# Generated by Django 6.0 on 2026-04-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0010_alter_registrar_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Folder', 'verbose_name_plural': '- b. List of Services'},
        ),
    ]
