# Generated by Django 6.0 on 2026-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chedorders',
            options={'verbose_name': 'Ched Memo Orders', 'verbose_name_plural': ' - a.  List of Compliances'},
        ),
        migrations.AddField(
            model_name='chedorders',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
