# Generated by Django 6.0.3 on 2026-04-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_abbrevation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='assignment',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='grade_section',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='gradesection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gradesection',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='school',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='parent_payment',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='tuitionfee',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tuitionfee',
            name='school',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='GradeSection',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TuitionFee',
        ),
    ]
