# Generated by Django 6.0.3 on 2026-04-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_schedule_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': 'List of Schools'},
        ),
    ]
