# Generated by Django 6.0.3 on 2026-04-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Lists of School'},
        ),
    ]
