# Generated by Django 6.0.3 on 2026-04-06 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrevation', models.CharField(blank=True, max_length=12)),
                ('started_at', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='school.school')),
            ],
            options={
                'verbose_name': 'Curriculums',
                'verbose_name_plural': 'Lists of Curriculums',
            },
        ),
    ]
