# Generated by Django 6.0.3 on 2026-04-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_curriculum_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='abbreviation',
        ),
    ]
