# Generated by Django 6.0.3 on 2026-04-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_rename_abbreviation_school_abbrevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='major',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
