# Generated by Django 6.0.3 on 2026-04-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_curriculum_curriculum_name_alter_school_abbrevation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Curriculum', 'verbose_name_plural': '- c. List of Curriculums'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': '- b. List of Programs'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': ' - a.  List of Schools'},
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='Approval Status'),
        ),
    ]
