# Generated by Django 6.0.3 on 2026-04-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_school_options_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': '- d. List of Books Holdings'},
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='Program Status'),
        ),
    ]
