# Generated by Django 6.0.3 on 2026-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_books_options_program_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(blank=True, max_length=100)),
                ('subject_desc', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': '- d. List of Books Holdings',
            },
        ),
    ]
