# Generated by Django 6.0.3 on 2026-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_chedorders_curriculum_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_unit',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='Approved Status'),
        ),
    ]
