# Generated by Django 6.0.3 on 2026-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_subject_subject_unit_alter_curriculum_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='unit_group',
            field=models.CharField(choices=[('I', 'I'), ('II', 'Approved'), ('III', 'Declined'), ('IV', 'Declined'), ('V', 'Declined')], default='V', max_length=10, verbose_name='Approved Status'),
        ),
    ]
