# Generated by Django 6.0 on 2026-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_books_options_books_author_books_collection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChedOrders',
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_group',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], default='V', max_length=10, verbose_name='Unit Group'),
        ),
    ]
