# Generated by Django 6.0 on 2026-04-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmo', '0003_chedorders_compliance_category'),
        ('school', '0023_remove_program_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ched_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ched_orders', to='cmo.chedorders'),
        ),
    ]
