# Generated by Django 6.0.3 on 2026-04-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_syllabus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'Syllaby', 'verbose_name_plural': '- f.  List of Syllabus'},
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='started_at',
        ),
    ]
