# Generated by Django 6.0.3 on 2026-04-06 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0005_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(default='Registrar', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='registrars/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='registrar_signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrars', to='school.school')),
            ],
            options={
                'verbose_name': 'Registrar',
                'verbose_name_plural': 'Registrars',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
