# Generated by Django 6.0.3 on 2026-04-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'Registrar', 'verbose_name_plural': 'Registrars'},
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='position',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='suffix',
        ),
    ]
