# Generated by Django 6.0.3 on 2026-04-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0003_alter_registrar_options_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='cabinet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='floor',
            field=models.TextField(blank=True),
        ),
    ]
