# Generated by Django 6.0.3 on 2026-04-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_registrar', '0004_folder_cabinet_folder_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'Registrar', 'verbose_name_plural': 'Registrars'},
        ),
        migrations.AlterField(
            model_name='folder',
            name='cabinet',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='floor',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
