# Generated by Django 6.0 on 2026-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmo', '0002_alter_chedorders_options_chedorders_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chedorders',
            name='compliance_category',
            field=models.CharField(choices=[('LEGAL_AUTHORITY', '01 - Legal Authority to Operate'), ('PROGRAM_PSGS', '02 - Program PSGs'), ('CURRICULUM_GENERAL_ED', '03 - Curriculum and General Education'), ('FACULTY_STAFF', '04 - Faculty and Staff'), ('STUDENT_AFFAIRS', '05 - Student Affairs'), ('QUALITY_ASSURANCE', '06 - Quality Assurance'), ('AUTONOMOUS_DEREGULATED', '07 - Autonomous / Deregulated'), ('RESEARCH_JOURNALS', '08 - Research and Journals'), ('COE_COD', '09 - COE / COD'), ('SCHOLARSHIPS_GRANTS', '10 - Scholarships / Grants'), ('HEALTH_SAFETY_FLEXIBLE', '11 - Health, Safety, Flexible Learning'), ('INTERNSHIP_PRACTICUM_CLINICAL', '12 - Internship / Practicum / Clinical'), ('SPORTS_WELLNESS', '13 - Sports and Wellness'), ('SPECIALIZED_PROGRAMS', '14 - Specialized Programs'), ('ETEEAP_LADDERIZED', '15 - ETEEAP / Ladderized'), ('GOVERNANCE_ADMIN', '16 - Governance / Administration')], default='LEGAL_AUTHORITY', max_length=50),
        ),
    ]
