# Generated by Django 5.1.3 on 2026-03-18 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRELIM_EXAM", "Prelim Exam"),
                    ("MIDTERM_EXAM", "Midterm Exam"),
                    ("PREFINAL_EXAM", "Pre-Final Exam"),
                    ("FINAL_EXAM", "Final Exam"),
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
