# Generated by Django 5.1.3 on 2026-03-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_student_user_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="abbrevation",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
