# Generated by Django 6.0.3 on 2026-04-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_curriculum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Curriculum', 'verbose_name_plural': '3. List of Curriculums'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': '1. List of Schools'},
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='abbrevation',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='abbrevation',
            new_name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='school',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=12)),
                ('started_at', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='school.school')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': '2. List of Programs',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='school.program'),
        ),
    ]
