# Generated by Django 6.0.3 on 2026-04-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_curriculum_abbreviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='abbreviation',
            new_name='abbrevation',
        ),
    ]
