# Generated by Django 6.0.3 on 2026-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_program_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='curriculum_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='abbrevation',
            field=models.CharField(blank=True, max_length=12, verbose_name='School Abbr'),
        ),
    ]
