# Generated by Django 6.0.3 on 2026-04-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': '- e. List of Books Holdings'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Book', 'verbose_name_plural': '- d. List of Subjects'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='program',
        ),
        migrations.AddField(
            model_name='books',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='school.subject'),
        ),
    ]
