# Generated by Django 6.0.3 on 2026-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_books_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_num', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='Curriculum Status'),
        ),
    ]
