# Generated by Django 6.0 on 2026-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_subject_unit_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': '- e. List of Books'},
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='collection',
            field=models.CharField(choices=[('Circulation', 'Circulation'), ('Filipiniana', 'Filipiniana'), ('References', 'References'), ('General', 'General')], default='General', max_length=20, verbose_name='Collections'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_group',
            field=models.CharField(choices=[('I', 'I - Major Subject'), ('II', 'II - Elective Subject'), ('III', 'III - Minor Subject'), ('IV', 'IV - Other'), ('V', 'V - Institutional Subject')], default='V', max_length=10, verbose_name='Unit Group'),
        ),
    ]
