# Generated by Django 6.0 on 2026-04-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_delete_chedorders_alter_subject_unit_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='school',
        ),
    ]
