# Generated by Django 6.0.3 on 2026-04-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrevation', models.CharField(blank=True, max_length=12, verbose_name='School Abbr')),
                ('school_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('started_at', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10, verbose_name='Approval Status')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': ' - a.  List of Schools',
            },
        ),
    ]
