# Generated by Django 6.0.3 on 2026-04-08 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': ' 1.1  List of Schools'},
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': ' - b. Grade Levels',
                'ordering': ['grade_name'],
                'unique_together': {('school', 'grade_name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('adviser', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.school')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': ' - c. Sections',
                'ordering': ['grade_level__grade_name', 'section_name'],
                'unique_together': {('school', 'grade_level', 'section_name')},
            },
        ),
    ]
