# Generated by Django 6.0.3 on 2026-04-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_options_gradelevel_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['grade_name'], 'verbose_name': 'Grade Level', 'verbose_name_plural': ' 1.2 Grade Levels'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['grade_level__grade_name', 'section_name'], 'verbose_name': 'Section', 'verbose_name_plural': ' 1.3 Sections'},
        ),
    ]
