# Generated by Django 6.0.3 on 2026-04-08 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_gradelevel_options_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Grade Level', 'verbose_name_plural': '1.2 Grade Levels'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': '1.1 List of Schools'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['grade_level__order', 'grade_level__name', 'name'], 'verbose_name': 'Section', 'verbose_name_plural': '1.3 Sections'},
        ),
        migrations.RenameField(
            model_name='gradelevel',
            old_name='grade_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='abbrevation',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='started_at',
            new_name='founded_date',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('school', 'name')},
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_name',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade_level', 'name')},
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='School Name'),
        ),
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': '1.4 Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='school',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': '1.5 Enrollments',
                'ordering': ['-enrolled_date'],
                'unique_together': {('student', 'section')},
            },
        ),
    ]
