# Generated by Django 6.0.3 on 2026-04-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_gradelevel_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_date'], 'verbose_name': 'Enrollment', 'verbose_name_plural': '1.6 Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Grade Level', 'verbose_name_plural': '1.3 Grade Levels'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['grade_level__order', 'grade_level__name', 'name'], 'verbose_name': 'Section', 'verbose_name_plural': '1.4 Sections'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Student', 'verbose_name_plural': '1.5 Students'},
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='schools.school')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': '1.2 Faculties',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_sections', to='schools.faculty'),
        ),
    ]
