"""
Django settings for school_management project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hv4w(=o-$hyx)3x2yr_o=1h(@29!rll^gygz59aeglt40yq+ou"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['lubumbashi2026.pythonanywhere.com','127.0.0.1']
AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "school_registrar",
    # "school_academics",
    # "apps.cmo",
    # "school",
    # "apps.school_a",
    
    "apps.accounts",
    "apps.guidance",

]



UNFOLD = {
    "SITE_TITLE": "ColdBlue IT Solution",
    "SITE_HEADER": "ColdBlue IT Solution",
    "SITE_SUBHEADER": "Institutions Management System",
    "SITE_URL": "/",
    "SITE_SYMBOL": "database",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "show_search": True,
    "show_all_applications": True,
    "show_search": True,
    "show_all_applications": True,
    # "THEME": "light",
    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        
    },
    
    "navigation_expanded": True,
}

# ===== Unfold main settings =====
#  UNFOLD = {
#     "SITE_TITLE": "Lubumbashi",
#     "SITE_HEADER": "Lubumbashi",
#     "SITE_SUBHEADER": "School Management System",
#     "SITE_URL": "/",
#     "SITE_ICON": None,
#     "SITE_LOGO": None,
#     "SITE_SYMBOL": "school",
#     "SHOW_HISTORY": True,
#     "SHOW_VIEW_ON_SITE": True,
#     "THEME": "light",
#     "COLORS": {
#         "primary": {
#             "50": "240 249 255",
#             "100": "224 242 254",
#             "200": "186 230 253",
#             "300": "125 211 252",
#             "400": "56 189 248",
#             "500": "14 165 233",
#             "600": "2 132 199",
#             "700": "3 105 161",
#             "800": "7 89 133",
#             "900": "12 74 110",
#             "950": "8 47 73",
#         },
#     },
#     "SIDEBAR": {
#         "show_search": True,
#         "navigation": [
#             {
#                 "title": "Registrar's Office",
#                 "permissions": ["school.unfold_conditions.is_student_or_registrar"],
#                 "items": itemA,
#             },
#             {
#                 "title": "Finance's Office",
#                 "permissions": ["school.unfold_conditions.is_student_or_registrar"],
#                 "items": [
#                     {
#                         "title": "Payments",
#                         "icon": "payments",
#                         "link": "/admin/school/payment/",
#                         "permissions": ["school.view_payment"],
#                     },
#                     {
#                         "title": "Tuition Fees",
#                         "icon": "receipt",
#                         "link": "/admin/school/tuitionfee/",
#                         "permissions": ["school.view_tuitionfee"],
#                     },
#                 ],
#             },
#             {
#                 "title": "School Administrator",
#                 "permissions": ["school.unfold_conditions.is_student_or_registrar"],
#                 "items": [
#                     {
#                         "title": "Schools",
#                         "icon": "school",
#                         "link": "/admin/school/school/",
#                         "permissions": ["school.view_school"],
#                     },
#                     {
#                         "title": "Users",
#                         "icon": "group",
#                         "link": "/admin/auth/user/",
#                         "permissions": ["auth.view_user"],
#                     },
#                     {
#                         "title": "Groups",
#                         "icon": "groups",
#                         "link": "/admin/auth/group/",
#                         "permissions": ["auth.view_group"],
#                     },
#                 ],
#             },
#         ],
#     },
# }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "school_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "school_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# LOGIN_REDIRECT_URL = 'post_login_redirect'
# LOGIN_URL = 'login'
# LOGOUT_REDIRECT_URL = 'login'
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
# MEDIA_ROOT = '/home/lubumbashi2026/school_management/media'
# MEDIA_URL = '/media/'
# STATIC_ROOT = '/home/lubumbashi2026/school_management/static'
# STATIC_URL = '/static/'


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']   # for development
STATIC_ROOT = BASE_DIR / 'staticfiles'     # for collectstatic



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'