# Generated by Django 6.0.3 on 2026-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0002_examattempt_questioncategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': '_1.5 Answers'},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'verbose_name': 'Attempt', 'verbose_name_plural': '_1.4 Exam Attempts'},
        ),
        migrations.AlterModelOptions(
            name='examinee',
            options={'verbose_name': 'Examinee', 'verbose_name_plural': '_1.1 Examinees'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': '_1.3 Questions'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': '_1.2 Exam Categories'},
        ),
        migrations.AddField(
            model_name='question',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='abstract_choices/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='abstract_choices/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='abstract_choices/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='abstract_choices/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('abstract', 'Abstract Reasoning')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
